sudo: required
services:
  - docker


before_install:
  - docker build -t tombo28/docker-react -f Dockerfile.dev .

script:
  - docker run tombo28/docker-react  npm test -- --coverage

deploy:
  provider:  elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-695828070322"
  bucket_path: "docker-react"
  on:
    branch:  master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
     